### ISSUE TITLE
additionalEntrypoints functionality needs to be improved

### ISSUE THREAD

**Issue by montalvomiguelo** [barrel/barrel-shopify#10]
1. Additional [entrypoints are being registered properly](https://imgur.com/a/6ZQS5DJ) but, there is no way to load them in the theme
2. Documentation for `additionalEntrypoints` needs to be created

```diff
  plugins: [
    shopify({
+     additionalEntrypoints: ['frontend/foo.ts', 'bar.ts']
    })
  ],

```
We would be able to load them like this:

* When they're relative to `sourceCodeDir` _(frontend/)_
```
  {%- render 'vite-tag' with '@/foo.ts' -%} # @ = frontend 
```

* When they're relateive to the root of the theme `themeRoot` 
```
  {%- render 'vite-tag' with '/bar.ts' -%}  # / = theme root
```

**Comment by ScottPolhemus** [comment]
@montalvomiguelo Please see [this commit on the additional-entrypoints-example branch](https://github.com/barrel/barrel-shopify/commit/1ba07071dd1b1732a382596940a6f0c8af5c16f2) for a working demo of the additionalEntrypoints option + the vite-tag snippet.

Your first example (`render 'vite-tag' with '@/foo.ts'`) works as-is because vite-tag does take resolve aliases into account.

The second example (`render 'vite-tag' with '/bar.ts'`) doesn't work because vite-tag treats all paths as being relative to the `entrypointsDir`, and we don't have special logic in place to handle the leading slash as an absolute path. (I think that's a pretty good idea though!) As it stands currently, it would be possible to load an entrypoint file from that location using either a path relative to the entrypointsDir (e.g. `render 'vite-tag' with '../../bar.ts'`) or by defining a new resolve alias in vite.config.js and using that.

Totally agree this stuff should be documented better, I'll work on that 😄

**Comment by montalvomiguelo** [comment]
Thanks for that @ScottPolhemus 

Yeah, It would be nice to use `/` for loading entries relative to themeRoot like [vite-ruby](https://vite-ruby.netlify.app/config/index.html#additionalentrypoints)

Please see #11 🙏
