### ISSUE TITLE
Changes to Liquid section files aren't showing on first reload

### ISSUE THREAD

**Issue by nboliver** [barrel/barrel-shopify#18]
When using `vite-plugin-shopify`, after changing a liquid file, you often have to manually hard reload the page in order to see your changes. This also seems to be happening with the SEED theme.

**Comment by montalvomiguelo** [comment]
@nboliver shopify-cli is responsible for hotreloading liquid files, which version are you using?

Try running the vite server and the shopify-cli in separate tabs https://imgur.com/a/5mJFDF6

**Comment by nboliver** [comment]
@montalvomiguelo Thanks for the quick reply. CLI is v2.29.0. Tried running in separate tabs but still seeing the issue - looks like there are some others experiencing similar issues with hot reloading, so I added to an issue in the CLI repo.

**Comment by montalvomiguelo** [comment]
Hi @nboliver 

I tried to reproduce this issue in the [hydrogen-theme](https://github.com/montalvomiguelo/hydrogen-theme) project but was unable to. I'm using the Shopify CLI v3.23.0

https://user-images.githubusercontent.com/5134470/213597619-e392e879-5533-411d-b50e-c1a74237d002.mp4

Could I have more details about your project so I can try to reproduce the issue?

**Comment by montalvomiguelo** [comment]
@nboliver, the Shopify CLI will hot reload local changes to the CSS and sections by default; that behavior does not work well in our workflow with Vite.

We need the page to reload when we edit the markup of our section files so that our changes are correctly applied. The Shopify CLI has the option to enable the page to reload.

```
 shopify theme dev --live-reload full-page
```

https://user-images.githubusercontent.com/5134470/213621808-46515ed8-7787-415d-90e4-d6ad71f15376.mp4
