### ISSUE TITLE
PublicDir: how to handle static assets (images)

### ISSUE THREAD

**Issue by kenji-twp** [barrel/barrel-shopify#23]
Hi guys, thanks for the work you put into this, it’s looking great!

I just wanted to know if there is a particular reason for forcing the publicdir to false, and how can I handle static assets.

As a basic example, I want to store a favicon in my repo, and my initial idea was using the vite publicdir, as it would be compiled (moved) to the shopify assets folder.

I tried to set the publicdir in vite config, but vte plugin shopify overrides it, forcing it to be ignored.

How/where can I put static images or other assets that I don’t want to be transformed, so they still are copied to the assets folder (and pushed to shopify)?

Would it be possible to add it as a plugin option, instead of forcing it?

Thanks again!

**Comment by montalvomiguelo** [comment]
Hey @kenji-twp,

We disable it by default because assets in the `public` directory get copied to the dist directory during build only.

You should be able to enable it in your vite config file using the `publicDir` option, then you could use [rollup-plugin-copy](https://github.com/vladshcherbin/rollup-plugin-copy) to copy those files during dev as well.

https://user-images.githubusercontent.com/5134470/201499506-efba6bd0-e90c-44b9-b601-d306d259d4cb.mp4

**Comment by kenji-twp** [comment]
Hey @montalvomiguelo, thanks so much for that! I was able to solve this following your instructions. I just ended up replacing rollup-plugin-copy with my own node script. Thank you!
