### ISSUE TITLE
vite-client.liquid snippet

### ISSUE THREAD

**Issue by jonathanmoore** [barrel/barrel-shopify#32]
Thank you so much for the work you're doing here!  This is incredibly helpful as we are in the process of redeveloping the dev tools we use to create official premium themes.  From our testing this seems to be the best approach we have come across, and we're working on a variation of a structure used at https://github.com/montalvomiguelo/hydrogen-theme that has the _island architecture_ concept.

The one roadblock that I anticipate us facing when getting through Shopify's very strict review process is the empty vite-client.liquid file that gets left behind and the render tag reference in layout/theme.liquid.

On my end, I'm contemplating making a few different changes:
1) Customizing our build/package scripts that manually strip out the empty snippet and the render tags for 'vite-client'
2) Forking the package to concatenate the vite-client snippet into the vite-tag snippet

Right now I'm leaning to the 2nd option even though it would result in the client script tag being duplicated in each of the vite-tag snippets—only in development.
<script src="http://localhost:5173/@vite/client" type="module"></script>

Instead of forking the package would you be open to official options to get around having an empty vite-client snippet and render reference?

**Comment by montalvomiguelo** [comment]
Hey @jonathanmoore :)

I'm glad you are considering using this plugin to build official premium themes.

Option 2 sounds pretty good to me to solve this problem and improve this plugin to help more people. Thanks a lot for calling it out!

* Prepend the `@vite/client` script tag to the `vite-tag.liquid` snippet during dev
  * Having duplicates should be OK since ES modules execute only once even if they're referenced in multiple `<script>` tags
* Deprecate/remove the `vite-client.liquid` snippet since it would not be needed anymore
* Update the readme file

cc @wturnerharris @oliverghuang
