### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [barrel/barrel-shopify#34]
Hi, is there support for React? We saw the Vue example branch, and we're trying to recreate that with React, but it doesn't seems to work. Do you have any example for that?

**Comment by montalvomiguelo** [comment]
Hey @AndreaPontrandolfo

* Supporting React would require loading [this script](https://github.com/vitejs/vite/issues/1984#issuecomment-778289660) in the liquid files e.g. `theme.liquid` during dev so that the HMR can work properly. It probably would need a separate plugin to handle that.
* Adding React to a Shopify theme has significant performance costs, currently, we don't have plans to support it.

Have you considered using [Preact](https://preactjs.com/)? 

_HMR works out of the box, and it's super lightweight. I created an example for you [here](https://github.com/barrel/barrel-shopify/tree/preact-example/themes/preact-shopify)_ (:
